### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by davidbrochart** [jupyter-server/jupyverse#100]
We currently have no other documentation than the README. Interactive documentation of the API comes for free with FastAPI, but we should start documenting the plugins and their configuration.

**Comment by jtpio** [comment]
The README seems to be redirecting to https://davidbrochart.github.io/jupyverse for the documentation. But is that page still relevant, now that the repo is under the `jupyter-server` organization?

The link is also on the repo home page:

![image](https://github.com/jupyter-server/jupyverse/assets/591645/e30a6bd9-6673-44a9-9821-83599aedf98b)

**Comment by jtpio** [comment]
Also the "About" section says " A Jupyter server based on FastAPI 🚀 ", while the README says: "A set of [Asphalt](https://asphalt.readthedocs.io/) components implementing a Jupyter server."

Is Asphalt based on FastAPI? Should one of the sentences be updated?

**Comment by davidbrochart** [comment]
Thanks, I just published the documentation on https://jupyter-server.github.io/jupyverse, and I opened #404.

> Is Asphalt based on FastAPI? Should one of the sentences be updated?

Yes, we use [asphalt-web](https://asphalt-web.readthedocs.io/en/latest/integrations.html#fastapi)'s FastAPI integration [here](https://github.com/jupyter-server/jupyverse/blob/a22737228772a76d577dd6af022bde28f4fb80bc/jupyverse_api/pyproject.toml#L32).
Both sentences are right, I think it's fine to have a shorter one in the "About" section, what do you think?

**Comment by jtpio** [comment]
Sure, or maybe the README can mention Alsphalt has a FastAPI integration?
