### ISSUE TITLE
Changing Build Backend (to Hatch?)

### ISSUE THREAD

**Issue by RobertRosca** [jupyter-server/jupyverse#209]
### Problem

- The main project and all plugins have `pyproject.toml`, `setup.py`, and `setup.cfg` to define various installation options, splitting up where options/dependencies can be configured
- Development install instructions, CI commands, and (now) devcontainer install all explicitly call `pip install ./plugins/...` for each plugin, and all of them need to be updated as plugins are added/removed/renamed
- Packaging requires individually building all pulgins and moving the files to `dist/`
- Creating new plugins (at least if you want them to be consistent with the current layout) requires creating these files/copying them from an existing plugin and modifying them

### Proposed Solution

[Hatch](https://github.com/pypa/hatch) has some features which would help:

- `pyproject.toml` contains all the configurations and dependencies so they're no longer spread out
- [Optional project dependencies](https://hatch.pypa.io/latest/config/metadata/#optional) and [local directory packages](https://hatch.pypa.io/latest/config/dependency/#local) can be used to allow for installation with the standard optional syntax, e.g. `pip install -e '.[plugins]'`, `pip install -e '.[plugins,retro]'`, `pip install -e '.[plugins,lab]'`
- Hatch has extensive [build](https://hatch.pypa.io/latest/build/) and [publish](https://hatch.pypa.io/latest/publish/) configurations, which should be able to build all juypverse and plugins for a release with one command
- Hatch has [project templates](https://hatch.pypa.io/latest/config/project-templates/), meaning a template can be provided which can be used to create new plugins, making it easier to set them up

In addition to that there are some other useful features:

- Hatch lets you define [environments with matrices](https://hatch.pypa.io/latest/environment/#matrix), simplifying the process of testing plugins like retro/lab which cannot be installed together
- Related to that, you can [have scripts attached to environments](https://hatch.pypa.io/latest/environment/#selection), meaning that a `lab` and `retro` environment could be defined with their respective plugin s as dependencies and with `serve` scripts, then `hatch run lab:serve` and `hatch run retro:serve` could both be ran, making it easier to check incompatible plugins without having to run install/uninstall commands

There are a lot of other features too which could be useful, but off the top of my head those are the main ones.

### Additional context

Jupyter Server, as well as a few other major projects, already use Hatch for their project management and build system.

**Comment by davidbrochart** [comment]
Thanks for bringing that up @RobertRosca!
You're right, Jupyter is moving to using Hatch in general, and the features you've listed would be very beneficial to Jupyverse.
As you seem to have a clear idea of how to proceed, would you like to open a PR? That would be great.

**Comment by RobertRosca** [comment]
Sure, I'll give it a go some time this week. Just wanted to check if it was a good idea before working on the PR :smile:

**Comment by RobertRosca** [comment]
That was very optimistic of me, since I went on holiday right after for over two weeks :sweat_smile: but I'm back now and just started on this.

**Comment by davidbrochart** [comment]
Awesome, and no worries!

**Comment by davidbrochart** [comment]
@RobertRosca I switched to hatch in #227. It should be equivalent to what we had before with setuptools, but there is none of the potential improvements your described in this issue.

**Comment by RobertRosca** [comment]
Ah nice, thanks for the update!

I wrote up the main project.toml file but ran into an issue with Hatch (https://github.com/pypa/hatch/issues/476) where having an environment with a relative path dependency caused an exception.

Without the ability to define the local plugins as additional dependencies to new environments you lose out on the parallel environment features, so I decide to wait until a fix before putting the PR up.

**Comment by RobertRosca** [comment]
My PR https://github.com/pypa/hatch/pull/484 was merged, solving this issue, but I'm currently at a conference, so I'll get back to this once that is finished.

**Comment by davidbrochart** [comment]
Nice, looking forward to it!
