### ISSUE TITLE
[Yjs] Stateful file manager for yjs

### ISSUE THREAD

**Issue by Wh1isper** [jupyter-server/jupyverse#247]
### Problem

1. All file changes are stored in the same db file, This can lead to performance problems (https://github.com/jupyter-server/jupyter_server_ydoc/issues/49)
2. Unedited files should be treated as static and previous collaboration records deleted (this means that the ydoc record for a file should be temporary), Otherwise, the user may rename the file and create a new one with the same name and then have problems

For example, if you create a new ipynb (Untitled.ipynb), write something and rename it, and then create another ipynb (Untitled.ipynb), the new Untitled.ipynb will not open on the front end...

### Proposed Solution

A file open and close related management should be added, yjs websocket connection can be seen as a file open, the crdt algorithm to solve the conflict of multiple users editing at the same time, when no user open the file, the file should be returned to "non-collaborative state"

This means that the life cycle of the file editing db should be bound to the user's access.

Also, I haven't figured out how to handle it when the service restarts or crashes, so maybe it needs an elegant startup to go with...

### Additional context

This problem may also be related to the horizontal scaling of the jupyverse

**Comment by davidbrochart** [comment]
> 2\. Otherwise, the user may rename the file and create a new one with the same name and then have problems

This issue should be mitigated with the [file ID service](https://github.com/jupyter-server/jupyter_server_fileid). There is an open [PR](https://github.com/jupyter-server/jupyverse/pull/244) in jupyverse.

**Comment by Wh1isper** [comment]
This is a history management issue, and a single fileid may not be sufficient for all cases

It seems to me that single disks on Linux platforms can use `ino` for file uniqueness distinction(https://github.com/jupyter-server/jupyter_server_fileid/issues/2#issuecomment-1276541629), as a way to link history files to real files, and remove history files when the link fails. But on other platforms, there doesn't seem to be a good means to do this without a service continuously monitoring the file system

I'm trying to implement a multi-user real-time collaborative data analysis service, but it may look similar to the problems Jupyter is currently facing but is different in nature
