### ISSUE TITLE
422 Unprocessable Entity when accessing server

### ISSUE THREAD

**Issue by matthewwiese** [jupyter-server/jupyverse#280]
## Description

When attempting to access the URL provided in the `To access the server, copy and paste this URL:` message, I encounter a 422 coded response with a JSON payload. Its contents are:

```json
{"detail":[{"loc":["query","args"],"msg":"field required","type":"value_error.missing"},{"loc":["query","kwds"],"msg":"field required","type":"value_error.missing"}]}
```

and a Firefox screenshot for easier reading:

![Screen Shot 2023-03-27 at 3 51 02 PM](https://user-images.githubusercontent.com/2100771/228051153-7a57a139-3ac2-42df-9455-ede4f61a4f09.png)

The URL only has the token query parameter populated:

```
http://0.0.0.0:8016/?token=2e669342-26cc-4ef9-bdb6-c3cc62810162
```

## Reproduce

I encounter this in both the `jupyverse` package from PyPI:

```
jupyverse --host=0.0.0.0 --port=8016
```

As well as the development mode using Hatch:

```
hatch run dev.jupyterlab:jupyverse --host=0.0.0.0 --port=8016
```

## Expected behavior

I think I should be greeted with a vanilla JupyterLab environment?

## Context
This occurs for me on macOS 12.6 (M1, but ARM is no longer an issue thanks to https://github.com/y-crdt/ypy/pull/115). Also on Rocky Linux 9.0

**Comment by davidbrochart** [comment]
Yes, I think it happens since FastAPI v0.95, and it's related to FastAPI-Users (see https://github.com/fastapi-users/fastapi-users/discussions/1176).
