### ISSUE TITLE
Uknown file `fileid.db` gets created each time jupyverse starts in a folder

### ISSUE THREAD

**Issue by oscar6echo** [jupyter-server/jupyverse#300]
## Description

Uknown file `fileid.db` gets created each time jupyverse starts in a folder.  
Is it important ? Can a user delete it ? Probably it should not be there ? or at least visible ?
Probably not serious, but worrying.

![image](https://github.com/jupyter-server/jupyverse/assets/2219383/a5d38be8-152b-4af6-8787-7b349d8db460)

## Reproduce

Open jupyverse in any folder in any mode.

**Comment by davidbrochart** [comment]
It's the path to the database used by the file ID manager (see [here](https://github.com/jupyter-server/jupyverse/blob/77c85f4e4e0d4f16e0f3b413f9e6f91742cfe16e/plugins/contents/fps_contents/fileid.py#L38)), which is responsible for tracking files and giving them a global ID.
I agree that it should at least start with a `.` to be hidden. It is fine to delete it, because it is created at startup.

**Comment by oscar6echo** [comment]
Ok, if it could be put out of the user's way e.g. `~/local/share/jupyter` next to its cousins `file_id_manager.db`, `jupyverse_users.db`, etc then it may stop confusing the user, unless there is a good reason to have it in the opened folder ?

Alternatively I tested with name `.fileid.db` and indeed it does not show up in jupyter lab; good enough.

**Comment by davidbrochart** [comment]
I'm not sure it can live in a Jupyter directory, because between two server sessions the file system could be completely different (say the local file system and a file system on the cloud, for instance), and it wouldn't make sense to mix the information from both file systems.

**Comment by oscar6echo** [comment]
Ok, I have inspected the `.fileid.db` with an sqlite browser and now have  better idea what all this is about.  
Indeed by definition this is relevant to the current directory.  

So yes the conclusion seems to be that renaming it to `.fileid.db` would solve the user unease with this UFO.
