### ISSUE TITLE
[Q] How do I get the current kernel ID?

### ISSUE THREAD

**Issue by NightMachinery** [jupyter-server/jupyverse#302]
With `jupyter lab`, I can do:

```
from ipykernel.connect import get_connection_file

get_connection_file()
```

And the kernel ID is visible in the file name. But this returns just a temp file in jupyverse:
```
/tmp/tmps2hicrwe.json
```

**Comment by davidbrochart** [comment]
I'm not sure having the kernel ID in the connection file name is specified, are even a good idea.
Why do you need to get the kernel ID from withing the kernel?

**Comment by NightMachinery** [comment]
> I'm not sure having the kernel ID in the connection file name is specified, are even a good idea. Why do you need to get the kernel ID from withing the kernel?

@davidbrochart Well, emacs-jupyter can connect to an existing kernel given its ID. (Though I now doubt this works with jupyverse, as it might rely on some specific behaviors in jupyter notebook.)

**Comment by davidbrochart** [comment]
I think all it needs is a connection file, right? Maybe it's finding the connection file based on the ID, because it assumes the connection file name has the ID in it.
Anyways, it might be better to align with what jupyter-server does. Do you want to open a PR?

**Comment by NightMachinery** [comment]
No, I have given up on running jupyverse.
