### ISSUE TITLE
Support RetroLab settings

### ISSUE THREAD

**Issue by davidbrochart** [jupyter-server/jupyverse#33]

**Comment by jtpio** [comment]
@davidbrochart could you elaborate on what needs to be done here?

Doing the local dev setup (for #54) led to some issues with the settings endpoint, so that might be related?

![image](https://user-images.githubusercontent.com/591645/133795831-02d28741-5193-4b63-83a6-910c31479beb.png)

Thanks!

**Comment by davidbrochart** [comment]
The default authentication method in jupyverse is token authentication, so in the server terminal you should see something like this:
```
To access the server, copy and paste this URL:
127.0.0.1:8000/?token=dec9f04c-6fc9-41e4-b3b0-2a90fbb8fdc6
```
The token query parameter is currently not present in the URL when a browser is automatically launched (see https://github.com/jupyter-server/fps/issues/23), so for now you can launch jupyverse like this:
```bash
jupyverse --no-open-browser
```
And manually copy the URL with the token in a browser window.
But for testing it is probably better to launch jupyverse without authentication:
```bash
jupyverse --authenticator.mode=noauth
```

**Comment by jtpio** [comment]
>  But for testing it is probably better to launch jupyverse without authentication:

Ah thanks looks like I was running the wrong command locally (`user` instead of `noauth`)
