### ISSUE TITLE
Handle the base url in the retro plugin

### ISSUE THREAD

**Issue by jtpio** [jupyter-server/jupyverse#55]
## Description

It looks like the `retrolab` plugin doesn't handle the base url yet:

https://github.com/jupyter-server/jupyverse/blob/e9ba1761bd43a5f907ec7c421941ae0dc4e95d43/plugins/retrolab/fps_retrolab/routes.py#L132

## Reproduce

This is for example the case when trying `jupyverse` on Binder.

## Expected behavior

Probably we can do something similar to the `jupyterlab` plugin.

## Context

This came up when testing `jupyverse` on Binder with a slight variation to use `retrolab`:

![image](https://user-images.githubusercontent.com/591645/133799435-663406c2-d948-4c7c-bdce-f9036859cffc.png)

**Comment by davidbrochart** [comment]
Yes, it's probably just a matter of updating retro with what was done in the jlab plugin.
