### ISSUE TITLE
Interactive docs broken

### ISSUE THREAD

**Issue by davidbrochart** [jupyter-server/jupyverse#63]
## Description

Interactive documentation is broken because `AttributeError: 'NoAuth' object has no attribute 'model'`.

## Reproduce

1. Start `jupyverse --no-open-browser`
2. Go to `http://127.0.0.1:8000/docs`
3. See the error in the termial.

`NoAuth` should have a "dummy" model, or we should "remove" it from the security schemes.
Any idea @frankie567?

**Comment by davidbrochart** [comment]
Setting `NoAuthAuthentication`'s `scheme` to `None` would work, but mypy currently fails because it expected a `SecurityBase`.
Could we make it `Optional[SecurityBase]` in [BaseAuthentication](https://github.com/fastapi-users/fastapi-users/blob/eb47dc8e752964a72ffa61333179a811771318ba/fastapi_users/authentication/base.py#L22)?

**Comment by frankie567** [comment]
Indeed, I didn't thought about OpenAPI generation. `None` could be a solution indeed. Could you live with a `type: ignore` comment?

```py
class NoAuthAuthentication(BaseAuthentication):
    def __init__(self, user: UserDB, name: str = "noauth"):
        super().__init__(name, logout=False)
        self.user = user
        self.scheme = None  # type: ignore
```

**Comment by davidbrochart** [comment]
> Could you live with a `type: ignore` comment?

Sure, thanks!
